### ISSUE TITLE
Error in non-root git dir

### ISSUE THREAD

**Issue by ciiiii** [darrenburns/dunk#3]
`FileNotFoundError` raised when executing `git diff | dunk` in  non-root git dir, It works in root git dir.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/28784251/161545137-51a7b9cb-3c3e-41f6-a0f2-77ceaa4adfbb.png">

**Comment by darrenburns** [comment]
I suspected this might happen but hadn't tested it yet. Thanks for the report!

**Comment by darrenburns** [comment]
Should be fixed in the new release 0.2.1a0
